export const WHATSAPP_EXTENSION_ID = "cfoaadkcknbhfcimkdekdodjhhokjmdc";
export const WHATSAPP_EXTENSION_ORIGIN = `chrome-extension://${WHATSAPP_EXTENSION_ID}`;
export const WHATSAPP_EXTENSION_MANIFEST_KEY =
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqcBwmJpiHj7P2Rtn5T3cFfRdjrUYfrtKYHIREwO6sDpWB6+iZPNQxigSPQQsZIbhctNCilL6CEea5LeiyfbNqAcmWUqZk/bBTe2Gd7epkgcrBfp/Dh5Aaz7tfuk5E7j+gDk55TZ2cIQwc/SGriudBuRHiEfBItIUHa7pIulSWmg/28nDg5sLHPDOa7nIDCFLY+s+FLYPZo2rYe772NoMJc8SMsVv3u8iTr17FigEYsmI0y1YSGBdsO1D6A4iIqPLLXR6UDKs+mvUGol+tK6zg4ZDoviWM763pkRdOocb657+IZUQaSzK106HBwh+eb3O8QbRhz+Ev/DnlYcsGVnCkwIDAQAB";

export const EXTENSION_PRESENCE_MAX_AGE_MS = 30_000;
export const EXTENSION_PAIRING_CODE_TTL_MS = 2 * 60_000;
export const EXTENSION_TOKEN_TTL_MS = 8 * 60 * 60_000;
