import { declararTools } from "./tipos";

export const TOOLS_AUTOMACAO = declararTools([
  {
    name: "crm_list_automation_rules",
    category: "read",
    rotulo: "Ver as regras automáticas",
    explicacao: "Mostra o que dispara cada regra, o que ela faz e se está ligada.",
    oQueToca: "Regras automáticas",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "crm_describe_automation_options",
    category: "read",
    rotulo: "Entender o que uma automação pode fazer",
    explicacao: "Mostra os gatilhos, ações, condições e proteções que existem de verdade.",
    oQueToca: "Regras automáticas",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "crm_list_automation_runs",
    category: "read",
    rotulo: "Ver o que as regras dispararam",
    explicacao: "Mostra as execuções recentes e o que foi adiado ou impedido.",
    oQueToca: "Regras automáticas",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "crm_create_automation_rule",
    category: "write",
    rotulo: "Preparar uma regra automática",
    explicacao: "Cria uma regra pausada para uma pessoa revisar antes de ligar.",
    oQueToca: "Regras automáticas",
    risco: "atencao",
    pacotes: ["organizar"],
  },
  {
    name: "crm_update_automation_rule",
    category: "write",
    rotulo: "Editar uma regra automática",
    explicacao: "Muda o gatilho, as condições ou as ações de uma regra existente.",
    oQueToca: "Regras automáticas",
    risco: "atencao",
    pacotes: ["organizar"],
  },
  {
    name: "crm_apply_automation_model",
    category: "write",
    rotulo: "Aplicar o fluxo modelo de atendimento",
    explicacao: "Cria modelos pausados de abordagem, avanço, entrega a uma pessoa e follow-up.",
    oQueToca: "Regras automáticas",
    risco: "atencao",
    pacotes: ["organizar"],
  },
  {
    name: "crm_set_automation_rule_active",
    category: "write",
    rotulo: "Ligar ou desligar uma regra automática",
    explicacao: "Faz uma regra começar ou parar de agir sozinha quando o gatilho acontecer.",
    oQueToca: "Regras automáticas",
    risco: "critico",
    pacotes: ["organizar"],
    apenasHumano: true,
  },
]);
